- name: restart dnsmasq
  service: name=dnsmasq state=restarted
  become: yes

- name: enable webapp
  systemd: name=gateway-web enabled=yes daemon_reload=yes
  become: yes

- name: restart webapp
  systemd: name=gateway-web state=restarted daemon_reload=yes
  become: yes

- name: enable daemon
  systemd: name=gateway-daemon enabled=yes daemon_reload=yes
  become: yes

- name: restart daemon
  systemd: name=gateway-daemon state=restarted daemon_reload=yes
  become: yes

- name: precompile assets
  shell: rails assets:precompile
  args:
    chdir: "~/gateway-web"
  become: yes
  become_user: "{{common.deploy_user}}"
