- name: Upload dnsmasq config
  template:
    src: dnsmasq_gateway.conf.j2
    dest: /etc/dnsmasq.d/dnsmasq_gateway.conf
  notify: restart dnsmasq

- name: Update sudoers file
  template:
    src: sudoers_gateway-web.j2
    dest: /etc/sudoers.d/gateway-web

- name: Install gems
  bundler:
    gemfile: "/home/{{common.deploy_user}}/gateway-web/Gemfile"
    state: present

- name: Upload env file
  template:
    src: env.j2
    dest: "~/gateway-web/.env"
    force: true
  become_user: "{{common.deploy_user}}"

- name: Upload gateway-web systemd unit file
  template:
    src: gateway-web.service.j2
    dest: /etc/systemd/system/gateway-web.service
  notify:
    - enable webapp
    - restart webapp

- name: Upload remote tunnel systemd unit file
  template:
    src: tunnel.service.j2
    dest: /etc/systemd/system/tunnel.service
