- name: Upload dnsmasq config
  template:
    src: gfwlist.conf.j2
    dest: /etc/dnsmasq.d/gfwlist.conf
  notify: restart dnsmasq

- name: Update sudoers file
  template:
    src: sudoers_gateway-web.j2
    dest: /etc/sudoers.d/gateway-web

- name: Install gems
  bundler:
    gemfile: "/home/{{common.deploy_user}}/gateway-web/Gemfile"
    state: present

- name: Upload env file
  template:
    src: rbenv.j2
    dest: "~/gateway-web/.rbenv-vars"
  become_user: "{{common.deploy_user}}"

- name: Upload gateway-web systemd unit file
  template:
    src: gateway-web.service.j2
    dest: /etc/systemd/system/gateway-web.service
  notify:
    - enable webapp
    - restart webapp

- name: Upload gateway-daemon systemd unit file
  template:
    src: gateway-daemon.service.j2
    dest: /etc/systemd/system/gateway-daemon.service
  notify:
    - enable daemon
    - restart daemon
