- name: Upload dnsmasq config
  template:
    src: gfwlist.conf.j2
    dest: /etc/dnsmasq.d/gfwlist.conf
  become: yes
  notify: restart dnsmasq

- name: Update sudoers file
  template:
    src: sudoers_gateway-web.j2
    dest: /etc/sudoers.d/gateway-web
  become: yes

- name: Install gems
  bundler:
    gemfile: "/home/{{ansible_user}}/tunnel-gateway-web/Gemfile"
    state: present
  become: yes

- name: Upload systemd unit file
  template:
    src: gateway-web.service.j2
    dest: /etc/systemd/system/gateway-web.service
  become: yes
  notify: restart webapp
