- name: Upload init
  template:
    src: obfsproxy-init.j2
    dest: /etc/init.d/obfsproxy
    owner: root
    group: root
    mode: 0755
  notify: restart obfsproxy

- name: Enable service
  service: name=obfsproxy enabled=yes
