- name: Checkout shadowsocks
  git:
    repo: https://github.com/shadowsocks/shadowsocks-libev.git
    dest: ~/shadowsocks-src/shadowsocks-libev
    force: yes
  become_user: "{{common.deploy_user}}"
  register: shadowsocks_checkout

- name: Compile shadowsocks
  shell: dpkg-buildpackage -b -us -uc -i
  args:
    chdir: "/home/{{common.deploy_user}}/shadowsocks-src/shadowsocks-libev"
  when: shadowsocks_checkout.changed

- name: Install shadowsocks
  shell: "dpkg -i shadowsocks-libev*.deb"
  args:
    chdir: "/home/{{common.deploy_user}}/shadowsocks-src"
  when: shadowsocks_checkout.changed
