- name: Checkout shadowsocks
  git:
    repo: https://github.com/shadowsocks/shadowsocks-libev.git
    dest: ~/shadowsocks-src/shadowsocks-libev
  register: shadowsocks_checkout

- name: Compile shadowsocks
  shell: dpkg-buildpackage -b -us -uc -i
  args:
    chdir: ~/shadowsocks-src/shadowsocks-libev
  when: shadowsocks_checkout.changed

- name: Install shadowsocks
  shell: "dpkg -i {{ansible_user_dir}}/shadowsocks-src/shadowsocks-libev*.deb"
  when: shadowsocks_checkout.changed
  become: yes
  notify:
    - restart shadowsocks
    - restart shadowsocks-tunnel
