- name: Change permissons for Shadowsocks config folder
  file:
    path: /etc/shadowsocks-libev
    owner: "{{common.deploy_user}}"
    group: "{{common.deploy_user}}"
    mode: 0755
    recurse: yes

- name: Enable service
  systemd: name=shadowsocks-libev-redir@config enabled=yes daemon_reload=yes
