- name: Install prerequisites
  apt:
    name: "{{item}}"
    cache_valid_time: 3600
    update_cache: yes
  with_items:
    - git
    - ntp

- name: Remove packages
  apt:
    name: "{{item}}"
    state: absent
    autoremove: yes
    purge: yes
  with_items:
    - cloud-init
